export const categories = [
  {
    category: "Work",
    icon: "💼",
    tasksToday: 2,
    subcategories: [
      { name: "Meetings", icon: "📅" },
      { name: "Projects", icon: "📊" },
      { name: "Emails", icon: "📧" },
      { name: "Reports", icon: "📄" },
      { name: "Deadlines", icon: "⏳" },
    ],
  },
  {
    category: "Personal",
    icon: "🏡",
    tasksToday: 2,
    subcategories: [
      { name: "Health & Fitness", icon: "🏃‍♂️" },
      { name: "Hobbies", icon: "🎨" },
      { name: "Family & Friends", icon: "👨‍👩‍👧" },
      { name: "Home Improvement", icon: "🔨" },
      { name: "Self-Care", icon: "🌸" },
    ],
  },
  {
    category: "Shopping",
    icon: "🛒",
    tasksToday: 2,
    subcategories: [
      { name: "Groceries", icon: "🥦" },
      { name: "Clothing", icon: "👗" },
      { name: "Electronics", icon: "💻" },
      { name: "Household Items", icon: "🏠" },
      { name: "Gifts", icon: "🎁" },
    ],
  },
  {
    category: "Education",
    icon: "🎓",
    tasksToday: 2,
    subcategories: [
      { name: "Courses", icon: "📚" },
      { name: "Assignments", icon: "📝" },
      { name: "Reading", icon: "📖" },
      { name: "Research", icon: "🔍" },
      { name: "Skills Development", icon: "💡" },
    ],
  },
  {
    category: "Travel",
    icon: "✈️",
    tasksToday: 2,
    subcategories: [
      { name: "Planning", icon: "📅" },
      { name: "Packing", icon: "🎒" },
      { name: "Reservations", icon: "🏨" },
      { name: "Itinerary", icon: "📍" },
      { name: "Sightseeing", icon: "🗺️" },
    ],
  },
  {
    category: "Finance",
    icon: "💰",
    tasksToday: 2,
    subcategories: [
      { name: "Bills", icon: "💳" },
      { name: "Budgeting", icon: "📊" },
      { name: "Savings Goals", icon: "💵" },
      { name: "Investments", icon: "📈" },
      { name: "Expenses Tracking", icon: "🧾" },
    ],
  },
  {
    category: "Events",
    icon: "🎉",
    tasksToday: 2,
    subcategories: [
      { name: "Birthdays", icon: "🎂" },
      { name: "Anniversaries", icon: "💖" },
      { name: "Holidays", icon: "🎆" },
      { name: "Gatherings", icon: "🥳" },
      { name: "Appointments", icon: "🗓️" },
    ],
  },
  {
    category: "Miscellaneous",
    icon: "📌",
    tasksToday: 2,
    subcategories: [
      { name: "Ideas", icon: "💡" },
      { name: "Reminders", icon: "⏰" },
      { name: "Clean-up Tasks", icon: "🧹" },
      { name: "Follow-ups", icon: "📞" },
      { name: "Future Plans", icon: "🗺️" },
    ],
  },
];
